CREATE SCHEMA IF NOT EXISTS OLIST_DB.SILVER;

CREATE OR REPLACE TABLE OLIST_DB.SILVER.CUSTOMERS AS
SELECT DISTINCT
    UPPER(TRIM(CUSTOMER_ID)) AS CUSTOMER_ID,
    UPPER(TRIM(CUSTOMER_UNIQUE_ID)) AS CUSTOMER_UNIQUE_ID,
    CUSTOMER_ZIP_CODE_PREFIX,
    UPPER(TRIM(CUSTOMER_CITY)) AS CUSTOMER_CITY,
    UPPER(TRIM(CUSTOMER_STATE)) AS CUSTOMER_STATE
FROM OLIST_DB.BRONZE.CUSTOMERS;

CREATE OR REPLACE TABLE OLIST_DB.SILVER.ORDERS AS
SELECT 
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    TO_TIMESTAMP(ORDER_PURCHASE_TIMESTAMP) AS ORDER_PURCHASE_TIMESTAMP,
    TO_TIMESTAMP(ORDER_APPROVED_AT) AS ORDER_APPROVED_AT,
    TO_TIMESTAMP(ORDER_DELIVERED_CARRIER_DATE) AS ORDER_DELIVERED_CARRIER_DATE,
    TO_TIMESTAMP(ORDER_DELIVERED_CUSTOMER_DATE) AS ORDER_DELIVERED_CUSTOMER_DATE,
    TO_TIMESTAMP(ORDER_ESTIMATED_DELIVERY_DATE) AS ORDER_ESTIMATED_DELIVERY_DATE
FROM OLIST_DB.BRONZE.ORDERS;
