CREATE SCHEMA IF NOT EXISTS OLIST_DB.GOLD;

CREATE OR REPLACE TABLE OLIST_DB.GOLD.PEDIDOS_COMPLETOS AS
SELECT 
    O.ORDER_ID,
    O.ORDER_STATUS,
    O.ORDER_PURCHASE_TIMESTAMP,
    C.CUSTOMER_CITY,
    C.CUSTOMER_STATE
FROM OLIST_DB.SILVER.ORDERS AS O
JOIN OLIST_DB.BRONZE.CUSTOMERS AS C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID;

 CREATE OR REPLACE VIEW OLIST_DB.GOLD.DASHBOARD_KPIs AS
SELECT 
    DATE_TRUNC('MONTH', ORDER_PURCHASE_TIMESTAMP) AS MES,
    COUNT(ORDER_ID) AS QTD_PEDIDOS,
    CUSTOMER_STATE
FROM OLIST_DB.GOLD.PEDIDOS_COMPLETOS
GROUP BY 1, 3;
