SELECT 
    CUSTOMER_STATE, 
    COUNT(ORDER_ID) AS TOTAL_PEDIDOS
FROM OLIST_DB.GOLD.PEDIDOS_COMPLETOS
GROUP BY CUSTOMER_STATE
ORDER BY TOTAL_PEDIDOS DESC;

SELECT * FROM OLIST_DB.GOLD.PEDIDOS_COMPLETOS LIMIT 10;
